---
- hosts: localhost
  connection: local
  tasks:
    - name: Example task
      shell: echo "Deploying on local machine with Docker image {{ docker_image }}"
      # Add your deployment tasks here
